master:
  image: jenkins:alpine
  container_name: jenkins
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true -Duser.timezone=Asia/Shanghai"
  ports:
    - "50000:50000"
    - "9091:8080"
  volumes:
    - /data/jenkins:/var/jenkins_home
    - /Users/yuanyuan/.m2:/root/.m2
    - /Users/yuanyuan/.npm:/root/.npm